- include: "{{ task }}.yml"

- name: list current directory
  shell: "ls -l"
  register: file_list

- name: print file list
  debug:
      var=file_list

#- name: upload the overcloud images to glance
#  shell: "source ~/stackrc; openstack overcloud image upload --update-existing"
