- include: "{{ task }}.yml"

- name: List images built
  shell: "ls -l {{ image_build_dir }}"
  when: task == 'build'

- name: List images imported
  shell: "ls -l {{ work_dir }}"
  when: task == 'import'

- name: Upload to the storage server using pubkey auth if requested
  shell:
      "time rsync -ave 'ssh -o StrictHostKeyChecking=no' {{ image_build_dir }}/{{ tar_file }} {{ storage_user }}@{{ storage_server }}:{{ storage_path }}/{{ ospd_version }}/"
  when: upload_to == 'remote'

- name: Upload the overcloud images to glance
  shell: |
      pushd {{ work_dir }}
      source ~/stackrc; openstack overcloud image upload --update-existing
  when: upload_to == 'glance'
